discord:
  token: "your_discord_bot_token_here"

aws:
  access_key_id: "your_aws_access_key_id"
  secret_access_key: "your_aws_secret_access_key"
  region_name: "your_aws_region"

storage:
  mode: "json" [options json or db]
  url: "sqlite:///your_database_path_here.db"
  